# Generated by Django 2.2.5 on 2019-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
