# Generated by Django 2.2.5 on 2019-09-27 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.IntegerField()),
                ('main', models.CharField(max_length=100)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Branch')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_code', models.IntegerField()),
                ('sub', models.CharField(max_length=100)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Branch')),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('unit', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('opening_stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('main_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Branch')),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category')),
                ('sub_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.SubCategory')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
